bugfix: CentOS init scripts did not work

diff --git a/buildfiles/centos/etc/init.d/appserver-fpm b/buildfiles/centos/etc/init.d/appserver-fpm
--- a/buildfiles/centos/etc/init.d/appserver-fpm
+++ b/buildfiles/centos/etc/init.d/appserver-fpm
@@ -6,10 +6,11 @@
 # Required-Stop:     $all
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: starts appserver-fpm
-# Description:       starts appserver-fpm using start-stop-daemon
+# Short-Description: starts/stops appserver-fpm
+# Description:       Control sript for the appserver-fpm. Makes use of /etc/init.d/functions
 ### END INIT INFO
 
+# Define constants holding our execution setup
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 BASE_PATH='/opt/appserver'
 DAEMON="${BASE_PATH}/sbin/php-fpm"
@@ -17,36 +18,49 @@ DAEMON_OPTS="-D -c /opt/appserver/etc/ -y /opt/appserver/etc/php-fpm.conf"
 NAME="appserver-fpm"
 DESC="appserver-fpm"
 PIDFILE="/var/run/${NAME}.pid"
-QUIET="--quiet"
-START_OPTS="--start ${QUIET} --background --chdir ${BASE_PATH} --make-pidfile --pidfile ${PIDFILE} --exec ${DAEMON} -- ${DAEMON_OPTS}"
-STOP_OPTS="--stop --pidfile ${PIDFILE}"
 
-test -x $DAEMON || exit 0
+# Include the functions file as we need it for the "killproc" command
+. /etc/init.d/functions
 
-set -e
+# Start script is implemented manually as we had problems with the "daemon" command
+# @TODO switch to "daemon" command for a unified look and feel
+start() {
+    printf "%-50s" "Starting $NAME..."
+    cd $BASE_PATH
+	PID=`$DAEMON $DAEMON_OPTS > /dev/null 2>&1 & echo $!`
+	#echo "Saving PID" $PID " to " $PIDFILE
+
+	if [ -z $PID ]; then
+	    printf "%s\n" "Fail"
+	else
+	    echo $PID > $PIDFILE
+	    printf "%s\n" "Ok"
+	fi
+}
+
+stop() {
+    printf "%-50s" "Stopping $NAME..."
+    killproc $NAME
+    RETVAL=$?
+    echo
+    [ $RETVAL -eq 0 ] && rm -f $PIDFILE
+    return $RETVAL
+}
 
 case "$1" in
   start)
-	echo -n "Starting $DESC: "
-	start-stop-daemon $START_OPTS
-	echo "$NAME."
+	start
 	;;
   stop)
-	echo -n "Stopping $DESC: "
-	start-stop-daemon $STOP_OPTS
-	echo "$NAME."
+	stop
 	;;
   restart|force-reload)
-	echo -n "Restarting $DESC: "
-	start-stop-daemon $STOP_OPTS
-	sleep 1
-	start-stop-daemon $START_OPTS
-	echo "$NAME."
+	stop
+	start
 	;;
   status)
-    echo -n "Status of $DESC: "
-    status -p ${PIDFILE} "$NAME"
-    ;;
+    status $NAME
+	;;
   *)
 	N=/etc/init.d/$NAME
 	echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
